apiVersion: v1
kind: Secret
metadata:
    name: my-secret
    namespace: default
data:
    #ENC[AES256_GCM,data:Ph9t0hCNMQTEYO9iDNauFirstZULCQ==,iv:+GuzXhS64jRCWAzguAvN8OyLiYOzuaEUgeGOk411yTw=,tag:rU8ZmZHaOUKmh1UKo+i6uA==,type:comment]
    password: ENC[AES256_GCM,data:ae1cMAO5lYIw9KBg,iv:SypzGPqL4oiZKXIJLz3M1w9U7/eZLg8AZrjxp1DspPE=,tag:MJBPjPfIcF+FNVjE1XQQCQ==,type:str]
    #ENC[AES256_GCM,data:Vph6jednglNAeqZOcejjFVzHzZ2z,iv:jkpGGLPGWqyRz4Hgz+zSunHiGKRBKfcK21BturEA03c=,tag:ULYTY3Rx87t/TSe1LCpOTQ==,type:comment]
    api-key: ENC[AES256_GCM,data:IgvK32YHbAE7vRJR,iv:+121fb1UV6+KBx5M9+ucXH4hQtWQ4u5/wcsYiOJjlXQ=,tag:5OJFymUGGIp8UhlvfAfFyA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:889546352481:key/3c2ee4fc-7abb-48f9-8bca-24d439be8e14
          created_at: "2025-06-02T11:15:07Z"
          enc: AQICAHhLPbTjGTLhVl5oDZTcbhFcmzea5NZqxNS42NYJwJ6XVQEnE6Dni1lwIJOZs+P0vugjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpbr+QjO1Hr+NqNjIAgEQgDvQUlManfTBIY8SMp1wMLHTGnpNtPVdy5xlO5cVrPIlewlGTgprQDJqmrdaiKrZztpcsUiLXPj/l8nAaw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-02T11:15:09Z"
    mac: ENC[AES256_GCM,data:DtYB5F020wddtbK74a9STQ5QMQXy622C5L1bpnmMHgof0UCCXlWdp79INI91uMoJNmIWJWAmU8bgXKqxkLAGy7CC4kcJ20XcdHFFLik0q6crtCBpHNpheJUi32yhpzRtevs3WT0JEaT6p2fdqDqoZTGbnQ7IDYmPqZ1oA3V/N+M=,iv:JfytklCmyll7Mzym/naBM3mnJE1kIQwu5A8H99Q6UnM=,tag:jGq45b0u58TLKuox8clCdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
