apiVersion: v1
kind: Secret
metadata:
    name: my-secret
    namespace: default
data:
    #ENC[AES256_GCM,data:KTgBEO9oTyIj0GiXXei0CIbnHKaqow==,iv:57FtaPpUwThIxGSDUujOU2QTk0clLQuqtXEK/Gj5lFU=,tag:1mQoO5UlKsYLdDViFyNk9g==,type:comment]
    password: ENC[AES256_GCM,data:tU7rPllZRPptNSE0,iv:qDD+Mm5i7mM6gS3QhrQml3zPJ5xGcMft3DLRwK3B2kA=,tag:r0HMkpNwp6oPsXLVoHCkRQ==,type:str]
    #ENC[AES256_GCM,data:DOlPhypGRwnA7OQHTG7gxurE8Dc6,iv:QZaWeX05kM3YE1PZVZZ2bL2GqWpucHEdAJPNhq3QQY8=,tag:/4Kh+WyUV6ANp13LbM34Ng==,type:comment]
    api-key: ENC[AES256_GCM,data:VLJCL6U/dTKv4Vjb,iv:QmDp5Dpgxqv6kiw+jHhxKlsFLX1wrF/nxFtsuzfuNHQ=,tag:mcaE9CJAuxrMQT23qi267g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:889546352481:key/3c2ee4fc-7abb-48f9-8bca-24d439be8e14
          created_at: "2025-06-02T10:00:01Z"
          enc: AQICAHhLPbTjGTLhVl5oDZTcbhFcmzea5NZqxNS42NYJwJ6XVQFNVheLrjkcggLKcuADxvc4AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMqvjUHOF5sh7uOGqUAgEQgDvA4zHuH80JDUpz6wWbGbzMNEtIdQvhBQnyYpsrIfvL8sNlvBfWWFUYldCCgeIvY/HjKEp/RVpBdK7cpQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-02T10:00:02Z"
    mac: ENC[AES256_GCM,data:t2NvTw6ejBgolxrW64Lt2BqQBah5W5Q6gXVTnFcxBGP+QGSWX+Vky+7tmm4DFQ0S9HF9z/IJ1aSMx+Q8L/2wWMV5bsLRUy+UFL2H5mXgPIX/fZ39wLDlD3IKOBG2YrjF5FKQ5x9DW1kVKlG/CLMHqyoGlNki7jwimoS31AWO5ko=,iv:eSdkIxKbyv1njajKGYE7HnQ1e7t2d2d7JJSsccA10Ao=,tag:7BTH8NinUJp+kg1tLaFNiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
